"""empty message

Revision ID: 3bd2cb09bc76
Revises: 
Create Date: 2019-04-05 05:11:44.289002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bd2cb09bc76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.String(length=30), nullable=True),
    sa.Column('goods_serlal_number', sa.String(length=30), nullable=True),
    sa.Column('shop_id', sa.String(length=30), nullable=True),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('orl_price', sa.Float(), nullable=True),
    sa.Column('present_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods')
    # ### end Alembic commands ###
